"""create visibility tables

Adds the two CBAC tables (RF23):
- project_category_visibility: 8 toggles per project (one per Quadro-37 category).
- project_attribute_visibility: per-attribute override; wins over the category.
Both tables use composite PK (project_id, key). Absence of a row = oculto.

Revision ID: 0013
Revises: 0012
Create Date: 2026-05-30 11:06:00.788261

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_attribute_visibility",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("attribute_key", sa.String(length=128), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attribute_key IN ('nome_projeto', 'descricao', 'local_execucao', 'tipo', 'porte', 'objetivos', 'descricao_produtos_servicos', 'licitacao', 'contratos', 'termo_encerramento', 'justificativas_projeto', 'impactos_projeto', 'indicadores_projeto', 'artefatos_produzidos', 'imagens_fotos', 'nome_stakeholders', 'funcao_projeto', 'publico_alvo', 'detalhes_equipe', 'treinamentos_equipes', 'tarefas_projeto', 'requisitos', 'escopo_planejado', 'escopo_executado', 'data_inicio', 'data_fim_planejada', 'data_fim_executada', 'entregas_realizadas', 'status_cronograma', 'custo_estimado', 'custo_realizado', 'justificativas_gastos', 'riscos_identificados', 'analise_qualitativa_riscos', 'analise_quantitativa_riscos', 'planejamento_respostas_riscos', 'monitoramento_riscos', 'custo_implementacao_mudanca', 'analise_custo_beneficio', 'impactos_mudanca', 'pontos_fortes', 'pontos_fracos', 'dificuldades_encontradas', 'providencias_tomadas')",
            name=op.f("ck_project_attribute_visibility_valid_attribute_key"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_attribute_visibility_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "attribute_key", name=op.f("pk_project_attribute_visibility")
        ),
    )
    op.create_table(
        "project_category_visibility",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("category_key", sa.String(length=64), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category_key IN ('conteudo_geral', 'stakeholders', 'escopo', 'cronograma', 'custos', 'riscos', 'mudancas', 'licoes_aprendidas')",
            name=op.f("ck_project_category_visibility_valid_category_key"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_category_visibility_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "category_key", name=op.f("pk_project_category_visibility")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_category_visibility")
    op.drop_table("project_attribute_visibility")
    # ### end Alembic commands ###
