"""create syntheses

Revision ID: 6f8a539c0ec0
Revises: 0014
Create Date: 2026-06-04 15:05:21.538546

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6f8a539c0ec0'
down_revision: str | None = '0014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syntheses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_project_ids', sa.JSON(), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("domain IN ('legal', 'health', 'sports', 'branding', 'gastronomy', 'other')", name=op.f('ck_syntheses_valid_domain')),
    sa.CheckConstraint("status IN ('draft', 'published')", name=op.f('ck_syntheses_valid_status')),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_syntheses_generated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_syntheses_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_syntheses'))
    )
    op.create_index(op.f('ix_syntheses_domain'), 'syntheses', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syntheses_domain'), table_name='syntheses')
    op.drop_table('syntheses')
    # ### end Alembic commands ###
