/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as DomainsIndexRouteImport } from './routes/domains.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as DomainsNewRouteImport } from './routes/domains.new'
import { Route as DomainsIdRouteImport } from './routes/domains.$id'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'
import { Route as ProjectsIdEditRouteImport } from './routes/projects.$id_.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsNewRoute = DomainsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DomainsRoute,
} as any)
const DomainsIdRoute = DomainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DomainsRoute,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/projects/$id_/edit',
  path: '/projects/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domains': typeof DomainsRouteWithChildren
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/domains/$id': typeof DomainsIdRoute
  '/domains/new': typeof DomainsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/community/': typeof CommunityIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/domains/$id': typeof DomainsIdRoute
  '/domains/new': typeof DomainsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/community': typeof CommunityIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domains': typeof DomainsRouteWithChildren
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/domains/$id': typeof DomainsIdRoute
  '/domains/new': typeof DomainsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/community/': typeof CommunityIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id_/edit': typeof ProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domains'
    | '/feed'
    | '/login'
    | '/register'
    | '/settings'
    | '/community/$slug'
    | '/domains/$id'
    | '/domains/new'
    | '/projects/$id'
    | '/projects/new'
    | '/community/'
    | '/domains/'
    | '/projects/'
    | '/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/login'
    | '/register'
    | '/settings'
    | '/community/$slug'
    | '/domains/$id'
    | '/domains/new'
    | '/projects/$id'
    | '/projects/new'
    | '/community'
    | '/domains'
    | '/projects'
    | '/projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/domains'
    | '/feed'
    | '/login'
    | '/register'
    | '/settings'
    | '/community/$slug'
    | '/domains/$id'
    | '/domains/new'
    | '/projects/$id'
    | '/projects/new'
    | '/community/'
    | '/domains/'
    | '/projects/'
    | '/projects/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainsRoute: typeof DomainsRouteWithChildren
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  CommunitySlugRoute: typeof CommunitySlugRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/new': {
      id: '/domains/new'
      path: '/new'
      fullPath: '/domains/new'
      preLoaderRoute: typeof DomainsNewRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/domains/$id': {
      id: '/domains/$id'
      path: '/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof DomainsIdRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id_/edit': {
      id: '/projects/$id_/edit'
      path: '/projects/$id/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DomainsRouteChildren {
  DomainsIdRoute: typeof DomainsIdRoute
  DomainsNewRoute: typeof DomainsNewRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsIdRoute: DomainsIdRoute,
  DomainsNewRoute: DomainsNewRoute,
  DomainsIndexRoute: DomainsIndexRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainsRoute: DomainsRouteWithChildren,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  CommunitySlugRoute: CommunitySlugRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdEditRoute: ProjectsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
