"""create theme suggestions

Adds the audit table for IA-suggested project domains (RF19). The consultant
either accepts a suggestion (which sets `projects.domain` and stamps
`accepted_*`) or ignores it; even ignored suggestions stay so the academic
protocol can compute categorization accuracy.

Revision ID: 0014
Revises: 0013
Create Date: 2026-05-30 11:26:28.491933

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "theme_suggestions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("suggested_domain", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("accepted_by", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "suggested_domain IN ('legal', 'health', 'sports', 'branding', 'gastronomy', 'other')",
            name=op.f("ck_theme_suggestions_valid_suggested_domain"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["users.id"],
            name=op.f("fk_theme_suggestions_accepted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_theme_suggestions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theme_suggestions")),
    )
    op.create_index(
        op.f("ix_theme_suggestions_project_id"), "theme_suggestions", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_theme_suggestions_project_id"), table_name="theme_suggestions")
    op.drop_table("theme_suggestions")
    # ### end Alembic commands ###
